Allow handling of vendor change option
openSUSE/zypp-plugin-spacewalk pull request #43
Opened 2020-09-28 13:00 UTC by mseidl

Handles allow vendor change when passed from the server now.

2020-09-28 15:24 UTC, mcalmer requested changes
What do you think about the suggested changes.

2020-09-28 15:24 UTC, mcalmer commented on actions/packages.py
> +            args.append("--allow-vendor-change")
```suggestion
```

2020-09-28 15:24 UTC, mcalmer commented on actions/packages.py
> +        elif not allow_vendor_change and self.dup_version == 2:
```suggestion
        elif self.dup_version == 2:
            if allow_vendor_change:
                args.append("--allow-vendor-change")
            else:
```

2020-09-28 15:25 UTC, mcalmer commented on actions/packages.py
> +            args.append("--allow-vendor-change")
Drop this part, we do it later. See below.

2020-10-05 12:34 UTC, mcalmer requested changes

2020-10-05 12:34 UTC, mcalmer commented on actions/packages.py
> +            args.append("--allow-vendor-change")
This can be removed

2020-10-05 12:34 UTC, mcalmer commented on actions/packages.py
>              args.append("--no-allow-vendor-change")
The indentation is wrong.

2020-10-08 13:48 UTC, mcalmer approved these changes
Looks good now

2020-10-08 13:49 UTC, mcalmer requested changes
Ahh, one problem found. We do not have the tooling in this project as we have in uyuni git.
Here the changelog should have the header.

2020-10-08 17:45 UTC, mcalmer approved these changes

2020-10-26 09:09 UTC, meaksh approved these changes

2020-10-27 16:04 UTC, merged